### ISSUE TITLE
guzzleHTTP 7 compatibility

### ISSUE THREAD

**Issue by editionslva** [markrogoyski/numverify-api-client-php#2]
Hello,
I have this error message on installing  (I suppose it is because my composer.json contains "guzzlehttp/guzzle": "^7.0") :
```
 Installation request for markrogoyski/numverify-api-client-php 1.* -> satisfiable by markrogoyski/numverify-api-client-php[v1.0.0].
ev] but these conflict with your requit-php v1.0.0 requires guzzlehttp/guzzle ^6.0 -> satisfiable by guzzlehttp/guzzle[6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1, 6.2.0, 6.2.1,r6.2.2, 6.2.3, 6.3.0, 6.3.1, 6.3.2, 6.3.3, 6.4.0, 6.4.1, 6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5, 6.5.x-dev] but these conflict with your requirements or minimum-stabements or minimum-stability.

```
Maybe your library accepts v7 and it is possible to edit the composer file ?
Thanks

**Comment by markrogoyski** [comment]
Hi @editionslva,

Thanks for your interest in the Numverify API client, and thanks for bringing this to my attention.

It might be as easy as just loosening the Guzzle constraint. I will investigate and get back to you on this.

Mark

**Comment by markrogoyski** [comment]
Hi @editionslva,

Guzzle v7 requires a minimum PHP version of 7.2. The current version of this library supports PHP 7.0 as a minimum so it will not work as is with Guzzle v7. I will release a new version of this library (2.0) that will target PHP 7.2 as a minimum version and require Guzzle 7.0. I'll try to prepare that as soon as I can and let you know when it is ready.

Mark

**Comment by editionslva** [comment]
Thank you very much for your responsiveness

**Comment by markrogoyski** [comment]
Hi @editionslva,

Version v2.0.0 of this library has been released: https://github.com/markrogoyski/numverify-api-client-php/releases/tag/v2.0.0

It now requires PHP v7.2 and Guzzle v7.0.

Using Composer to install the library will bring in Guzzle v7 automatically.
```bash
$ php composer.phar require markrogoyski/numverify-api-client-php:2.*
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 7 installs, 0 updates, 0 removals
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing psr/http-client (1.0.1): Loading from cache
  - Installing ralouphie/getallheaders (3.0.3): Loading from cache
  - Installing guzzlehttp/psr7 (1.7.0): Loading from cache
  - Installing guzzlehttp/promises (1.4.0): Loading from cache
  - Installing guzzlehttp/guzzle (7.1.1): Loading from cache
  - Installing markrogoyski/numverify-api-client-php (v2.0.0): Downloading (100%)
guzzlehttp/psr7 suggests installing laminas/laminas-httphandlerrunner (Emit PSR-7 responses)
guzzlehttp/guzzle suggests installing psr/log (Required for using the Log middleware)
Writing lock file
Generating autoload files
```

You should be able to install it now.

Thank you for your interest in this library.
Mark

**Comment by editionslva** [comment]
Perfect, I just made a PR to include the optional country parameter in validation. The phone number is often provided in local format and it is useless to format in international since the API can do it for you : https://numverify.com/documentation
